// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FastTranslator
{
    internal sealed partial class Vsix
    {
        public const string Id = "FastTranslator.b0053719-afbe-4e28-ab6f-989873cf23b9";
        public const string Name = "FastTranslator";
        public const string Description = @"Быстрый перевод выделенного текста с английского на русскийБыстрый ";
        public const string Language = "ru-RU";
        public const string Version = "1.0";
        public const string Author = "Артём Александрович Корчагин";
        public const string Tags = "";
    }
}
